name: Ikuuu Check-in

on:
  schedule:
    - cron: '30 5 * * *' # Run job every day at 05:30 UTC

jobs:
  checkin:
    name: Run script
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests notify

    - name: Run Script
      env:
        ikuuu: ${{ secrets.IKUUU }}
      run: |
        python your_script.py
