name: 'Automated script run'
on:
  schedule:
    - cron: '10 6 * * *'  # 这会每分钟运行一次，你需要根据你的需求修改这个 cron 语句
  workflow_dispatch:  # 允许手动触发

jobs:
  script_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
         python-version: 3.7

      - name: Install dependencies
        run: pip install requests  # 根据你的实际情况添加需要的依赖
      # - name: Run script
      #   env:
      #    ikuuu: '3209144611@qq.com&2015xiaoxin.'
      #   run: python ikuuu2.py  # 你需要根据你实际情况替换 <your_script>
      - name: Run script
        env:
         gw: '3209144611&2015xiaoxin.'
        run: python gw.py  # 你需要根据你实际情况替换 <your_script>


        

      # - name: Install dependencies
      #   run: pip install pycryptodome
      # - name: Run script
      #   env:
      #    mi_account: '17637011017'
      #    mi_password: '2015xiaoxin.'
      #   run: python miui.py 
