name: 'Automated script run'
on:
  schedule:
    - cron:  '59 23 * * *' # 每日23:59运行
    # - cron: '0 0 6,8,20 * * *' # 在每个月的6号，8号和20号的00:00运行
    # - cron:  '59 23 * * *'  
    # - cron "0 0 6,8,20 * * *" script-path=yysign.py
    #,tag=匹配cron用
  workflow_dispatch:  # 允许手动触发

jobs:
  script_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
         python-version: 3.7

      - name: Install dependencies
        run: pip install requests  # 根据你的实际情况添加需要的依赖
      # - name: Run script
      #   env:
      #    ikuuu: ${{ secrets.IKUUU }}
      #   run: python ikuuu2.py  # 你需要根据你实际情况替换 <your_script>
      
      # - name: Run script
      #   env:
      #    gw: '3209144611&2015xiaoxin.'
      #   run: python gw.py  # 你需要根据你实际情况替换 <your_script>
      
      # - name: Run script
      #   env:
      #    yyusername: ${{ secrets.YYUSERNAME }}
      #    yypassword: ${{ secrets.YYPASSWORD }}
        
      #   run: python yysign.py  # 你需要根据你实际情况替换 <your_script>


        

      - name: Install dependencies
        run: pip install pycryptodome
      - name: Run script
        env:
         mi_account: ${{ secrets.ACCOUNT }}
         mi_password: ${{ secrets.PASSWORD }}
        run: python miui.py 
